### PR TITLE
Add stone/lbs weight unit option

### LINKED ISSUE #2: Add Stone as a weight measurement?
Great little PC tool thank you, finally a way to re purpose my Wii Boards :P
Can you possibly add Stone please? 

Thank You :)

### PR DESCRIPTION
**Pull request by carlansell94**
Add the option to view weight in stone/lbs. This also adds a unit selector to the top of the window to make unit selection more explicit, replacing the previous label-clicking functionality. There are a few formatting tweaks, mainly making elements slightly smaller, to fit this in.

Closes #2.

### CODE REVIEW

**Comment by schellingb** [comment]
Hey there!
Thank you for this PR, I merged it and did a tiny bit of cleanup (dbe6503) and also changed app.config and the vcproj file to run on all .NET versions (bce6285). So we don't require installing any framework or upgrade and run out of the gate everywhere on Windows 7 and upwards (Vista I'm not sure, and earlier versions than that didn't have .NET pre-installed).
Thanks again and cheers, going to close #2 now after all these years :-)

**Comment by carlansell94** [comment]
Hi,

That's great, thanks. If you couldn't already tell, I've never worked with .NET before (nor C# for that matter), so I let Visual Studio do what it recommended in terms of framework version. Your solution sounds much better :)

And thanks for making this app, it's great we're able to re-purpose these old boards for something useful.

**Comment by Ploggy** [comment]
Haha amazing! :) thank you for adding this carlansell94.

**Comment by Ploggy** [comment]
Had a quick test of the new stone/lbs option :)
looks like it may be a little bugged..
I just checked my weight which says I'm 13 stone (which is right) but the reading can fluctuate between 13 stone 0lbs and 13 stone 13lbs lol (I understand maybe a 1lb difference but not 13lbs!) 
My guess is the app could be trying to show 12 stone 13 lbs but the 13 isn't changing to 12?, though I can make the number change to 12 stone if I lift off the Wii Fit Board a little so its not stuck or anything so I'm not sure.

**Comment by carlansell94** [comment]
Yeah sorry about that, just realised it's missing Math.Floor when calculating the stone value, so it's rounding the value up if it's over half a stone.

Easy one to fix though :)

**Comment by Ploggy** [comment]
Ahh, nice one thank you!

**Comment by carlansell94** [comment]
Created a new PR to fix. Sorry schellingb, looks like I inadvertently caused this when tweaking the output formatting.

**Pull request merged**
